title: "projet_systeme_strictement_hyperbolique_partie2"
logo: img/nny.jpg
description: "Simulation numérique de la dynamique des gaz en 1D – Équations d’Euler"
show_downloads: true
theme : projet
lang :fr
